server.port=8080
spring.application.name=Dashboard Financiero

# Ruta al directorio con los CSVs del proyecto principal
# Por defecto busca en el directorio actual de ejecucion
datos.ruta=./datos
spring.thymeleaf.cache=false
